#ifndef __EVENT_H__
#define __EVENT_H__

enum Events
{
	ADD_REGULAR_GRAMMAR,
	ADD_REGULAR_EXPRESSION,
	ADD_FINITE_AUTOMATA,
	UPDATE_REGULAR_GRAMMAR,
	UPDATE_REGULAR_EXPRESSION,
	UPDATE_FINITE_AUTOMATA
};

#endif // !__EVENT_H__